# required
minimum_reviewers: 2
build_steps:
 - Gemfile bundle install
 - Gemfile bundle exec ruby test/test.rb
# optional
merge: true
org_mode: true
timeout: 1805
shell: /bin/bash
env:
 BUNDLE_GEMFILE: Gemfile

