minimum_reviewers: 2
merge: false
build_steps:
 - env
 - gem env
 - which bundle
 - which gem
 - bundle install
 - /usr/local/bin/gem list |grep graph
 - gem list
 - bundle exec ruby test/test.rb
org_mode: true
timeout: 1803
